### ISSUE TITLE
leveldb recover core dump

### ISSUE THREAD

**Issue by gandalf000** [google/leveldb#383]
```
#0  0x00007f86744a3925 in raise () from /lib64/libc.so.6
#1  0x00007f86744a5105 in abort () from /lib64/libc.so.6
#2  0x00007f867449ca4e in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f867449cb10 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000698b9f in leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Insert (this=0x176fe48, key=@0x7f8655ea3018: 0x2482000 "T\002") at ./db/skiplist.h:344
#5  0x00000000006980d8 in leveldb::MemTable::Add (this=0x176fe00, s=14391995, type=leveldb::kTypeValue, key=..., value=...) at db/memtable.cc:105
#6  0x00000000006a9377 in leveldb::(anonymous namespace)::MemTableInserter::Put (this=0x7f8655ea31d0, key=..., value=...) at db/write_batch.cc:118
#7  0x00000000006a9044 in leveldb::WriteBatch::Iterate (this=0x7f8655ea32c0, handler=0x7f8655ea31d0) at db/write_batch.cc:59
#8  0x00000000006a9462 in leveldb::WriteBatchInternal::InsertInto (b=0x7f8655ea32c0, memtable=0x176fe00) at db/write_batch.cc:133
#9  0x00000000006841bf in leveldb::DBImpl::RecoverLogFile (this=0x186a300, log_number=10947, edit=0x7f8655ea35d0, max_sequence=0x7f8655ea3468) at db/db_impl.cc:426
#10 0x0000000000683b89 in leveldb::DBImpl::Recover (this=0x186a300, edit=0x7f8655ea35d0) at db/db_impl.cc:348
```

same key

**Comment by cmumford** [comment]
Do you still have this database?

**Comment by cmumford** [comment]
Closing due to no feedback. Feel free to reopen if desired.
