### ISSUE TITLE
Error Running levelDb on Windows

### ISSUE THREAD

**Issue by ddhtuio** [google/leveldb#687]
We are running a project that uses levelDB from a linux docker container and receive the following error when the container is running on Windows and attempting to map volumes of database storage. Any help would be appreciated.

```
io.fusesource.leveldbjni.internal.NativeDB$DBException: IO error: /htu/data/database/mainnet/index: Invalid argument
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:200) ~[leveldbjni-all-1.18.3.jar:1.8]
        at org.fusesource.leveldbjni.internal.NativeDB.open(NativeDB.java:218) ~[leveldbjni-all-1.18.3.jar:1.8]
        at org.fusesource.leveldbjni.JniDBFactory.open(JniDBFactory.java:168) ~[leveldbjni-all-1.18.3.jar:1.8]
        at io.htu.db.LeveldbDatabase.open(LeveldbDatabase.java:84) [htu.jar:6eb8bea]
        at io.htu.db.LeveldbDatabase.<init>(LeveldbDatabase.java:55) [htu.jar:6eb8bea]
        at io.htu.db.LeveldbDatabase$LeveldbFactory.open(LeveldbDatabase.java:237) [htu.jar:6eb8bea]
        at io.htu.db.LeveldbDatabase$LeveldbFactory.<init>(LeveldbDatabase.java:229) [htu.jar:6eb8bea]
        at io.htu.Core.start(Core.java:143) [htu.jar:6eb8bea]
        at io.htu.cli.htuCli.startCore(htuCli.java:225) [htu.jar:6eb8bea]
        at io.htu.cli.htuCli.start(htuCli.java:213) [htu.jar:6eb8bea]
        at io.htu.cli.htuCli.start(htuCli.java:147) [htu.jar:6eb8bea]
        at io.htu.cli.htuCli.main(htuCli.java:61) [htu.jar:6eb8bea]
        at io.htu.cli.htuCli.main(htuCli.java:71) [htu.jar:6eb8bea]
        at io.htu.Main.main(Main.java:36) [htu.jar:6eb8bea]
```

Thanks,
Dave

**Comment by cmumford** [comment]
Can you reproduce this in C++?

**Comment by cmumford** [comment]
Hopefully you can get support on a docker forum. Sorry, we just don't do Java wrappers here. If you can repro in C++ please reopen.
