### ISSUE TITLE
leveldb not found

### ISSUE THREAD

**Issue by bwanaaa** [google/leveldb#786]
leveldb is present

```
# packages in environment at /home/stefan/anaconda3/envs/TF:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.9.0                    py37_0  
asn1crypto                1.3.0                    py37_0  
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
blinker                   1.4                      py37_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.1.1                      0  
cachetools                3.1.1                      py_0  
certifi                   2019.11.28               py37_0  
cffi                      1.14.0           py37h2e261b9_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      py37_0  
cryptography              2.8              py37h1ba5d50_0  
cssselect2                0.2.1                      py_0    conda-forge
cudatoolkit               10.1.243             h6bb024c_0  
cudnn                     7.6.5                cuda10.1_0  
cupti                     10.1.168                      0  
dbus                      1.13.12              h746ee38_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py37_0  
expat                     2.2.6                he6710b0_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.2                    py37_0  
glib                      2.63.1               h5a9c865_0  
gmp                       6.1.2                h6c8ec71_1  
google-auth               1.11.2                     py_0  
google-auth-oauthlib      0.4.1                      py_2  
google-pasta              0.1.8                      py_0  
grpcio                    1.27.2           py37hf8bcb03_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.10.0           py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
importlib_metadata        1.5.0                    py37_0  
intel-openmp              2020.0                      166  
ipykernel                 5.1.4            py37h39e3cac_0  
ipython                   7.13.0           py37h5ca1d4c_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
jedi                      0.16.0                   py37_0  
jinja2                    2.11.1                     py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
ld_impl_linux-64          2.33.1               h53a641e_7  
leveldb                   1.20                 hf484d3e_1  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.11.4               hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.9                hea5a465_1  
libxslt                   1.1.33               h7d1a2b0_0  
lxml                      4.5.0            py37hefd8a0e_0  
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h7b6447c_0  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
nbconvert                 5.6.1                    py37_0  
nbformat                  5.0.4                      py_0  
ncurses                   6.2                  he6710b0_0  
notebook                  6.0.3                    py37_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
oauthlib                  3.1.0                      py_0  
olefile                   0.46                     py37_0  
openssl                   1.1.1d               h7b6447c_4  
opt_einsum                3.1.0                      py_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
parso                     0.6.1                      py_0  
pcre                      8.43                 he6710b0_0  
pexpect                   4.8.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1  
plyvel                    1.2.0                    pypi_0    pypi
prometheus_client         0.7.1                      py_0  
prompt_toolkit            3.0.3                      py_0  
protobuf                  3.11.4           py37he6710b0_0  
ptyprocess                0.6.0                    py37_0  
pyasn1                    0.4.8                      py_0  
pyasn1-modules            0.2.7                      py_0  
pycparser                 2.19                     py37_0  
pygments                  2.5.2                      py_0  
pyjwt                     1.7.1                    py37_0  
pyopenssl                 19.1.0                   py37_0  
pyqt                      5.9.2            py37h05f1152_2  
pyrsistent                0.15.7           py37h7b6447c_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0  
pyzmq                     18.1.1           py37he6710b0_0  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.1                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h7b6447c_5  
reportlab                 3.5.26           py37he686d34_0  
requests                  2.23.0                   py37_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.0                        py_0  
scipy                     1.4.1            py37h0b6359f_0  
send2trash                1.5.0                    py37_0  
setuptools                46.0.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.14.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
sqlite                    3.31.1               h7b6447c_0  
svglib                    0.9.3                    py37_0    conda-forge
tensorboard               2.1.0                     py3_0  
tensorflow                2.1.0           gpu_py37h7a4bb67_0  
tensorflow-base           2.1.0           gpu_py37h6c5654b_0  
tensorflow-estimator      2.1.0              pyhd54b08b_0  
tensorflow-gpu            2.1.0                h0d30ee6_0  
termcolor                 1.1.0                    py37_1  
terminado                 0.8.3                    py37_0  
testpath                  0.4.4                      py_0  
tinycss2                  1.0.2                      py_1    conda-forge
tk                        8.6.8                hbc83047_0  
tornado                   6.0.4            py37h7b6447c_1  
traitlets                 4.3.3                    py37_0  
urllib3                   1.25.8                   py37_0  
wcwidth                   0.1.8                      py_0  
webencodings              0.5.1                    py37_1  
werkzeug                  1.0.0                      py_0  
wheel                     0.34.2                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h7b6447c_0  
xz                        5.2.4                h14c3975_4  
zeromq                    4.3.1                he6710b0_3  
zipp                      2.2.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```
my python is ok

```
(TF) stefan@4930:~/Dropbox/aPython$ which python
/home/stefan/anaconda3/envs/TF/bin/python
(TF) stefan@4930:~/Dropbox/aPython$ python -V
Python 3.7.6


```

but no leveldb

```
(TF) stefan@4930:~/Dropbox/aPython$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import leveldb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'leveldb'
>>> 

```

**Comment by bwanaaa** [comment]
same thing happens on a windows install of anaconda with 'conda install leveldb'
leveldb is present on 'conda list'
but

 ```
G:\Dropbox>python
Python 3.8.2 | packaged by conda-forge | (default, Mar  5 2020, 17:29:01) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import leveldb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'leveldb'
>>>
```

**Comment by cmumford** [comment]
hi @bwanaaa. This project doesn't create or distribute a Python wrapper or implementation of leveldb. There are a few different ones, so I'm not sure which one you are using. I suggest finding the project site for your package and posting your question there. Good luck.
