### ISSUE TITLE
"Corruption: not an sstable (bad magic number)" error in version 1.20

### ISSUE THREAD

**Issue by Arshiya95** [google/leveldb#864]
Hi,

We have a java process which uses leveldb for writing the key value pairs to disk and reads those key value pairs on condition basis. We have integrated leveldb with our java application using leveldb-jni-all.jar. Currently we are using leveldb version 1.20 and jni version 1.8.1 in our application .
OS          : RHEL 7.4 
File System : xfs

We are frequently facing the below exception and unable to find the root cause . Is there any fix that went around this in the latest leveldb(v1.22) ?

Corruption: not an sstable (bad magic number)
org.iq80.leveldb.DBException: Corruption: not an sstable (bad magic number)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:160)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:121)
        .
		.
		.
Caused by: org.fusesource.leveldbjni.internal.NativeDB$DBException: Corruption: not an sstable (bad magic number)
        at org.fusesource.leveldbjni.internal.NativeDB.checkStatus(NativeDB.java:202)
        at org.fusesource.leveldbjni.internal.NativeDB.write(NativeDB.java:287)
        at org.fusesource.leveldbjni.internal.JniDB.write(JniDB.java:157)
        ... 8 more

**Comment by pwnall** [comment]
I think we had some `fsync` fixes. We definitely had a durability fix on macOS. If your system has power failures, these fixes could be relevant. If you're always able to cleanly shutdown your computers / VMs, the fixes wouldn't make a difference.

**Comment by Arshiya95** [comment]
Thank you for the update . 
But we are running the application over Linux and we don't see any power shutdowns .
